完成材料与你手册的翻译，修正部分主文件翻译
HaloSense/TiC3-Translation pull request #15
Opened 2022-03-26 14:34 UTC by TartaricAcid

依据最新英文版文件修改核对而来，修复了部分排版错误

2022-03-26 15:22 UTC, ChuijkYahus requested changes
大概看了一下

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/armor/pants.json
> +        "低耐久",
```suggestion
        "低耐久值",
```
前后统一

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/intro/partbuilder.json
> +        "text": "制作部件及其简单：制作一个空白模具，将其放入模具槽。选择你想制作的工具部件，然后再放入一种徒手可以塑型的软性材料，就可以获得部件了。",
```suggestion
        "text": "制作部件极其简单：制作一个空白模具，将其放入模具槽。选择你想制作的工具部件，然后再放入一种徒手可以塑形的软性材料，就可以获得部件了。",
```
```suggestion
        "text": "制作部件极其简单：制作一个空白模具，将其放入模具槽。选择你想制作的工具部件，然后再放入一种徒手可以塑型的软性材料，就可以获得部件了。",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/modifiers/abilities.json
> +            "text": "能力需要装载进能力槽中。几乎所有的工具初始都会携带一个能力槽，且最多只能装载一个能力，所以最好在选择强化时明智一些。",
```suggestion
            "text": "能力需要加持进能力槽中。几乎所有的工具初始都会携带一个能力槽，且最多只能加持一个能力，所以最好在选择强化时明智一些。",
```
这里本来库里的用词是“加持”
有必要就统一一下吧

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/modifiers/abilities.json
> +            "text": "能力是一种非常强大的工具强化，它甚至可以彻底改变一个工具。诸如精准采集和自动冶炼这样的强化非常瞩目，它们彻底改变了采掘矿物的效果，而双持强化则让工具更便于操作。"
```suggestion
            "text": "能力是一种非常强大的工具强化，它甚至可以彻底改变一个工具。诸如精准采集和自动烧炼这样的强化非常瞩目，它们彻底改变了采掘矿物的效果，而双持强化则让工具更便于操作。"
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/modifiers/defense.json
> +            "text": "同许多其他的强化属性一样，防御强化需要一个强化槽以装载。很显然，护甲的防御槽越多，那么升级槽也就越少，这算是牺牲了功能而获得了保护。",
```suggestion
            "text": "同许多其他的强化属性一样，加持防御强化会消耗防御槽。很显然，护甲的防御槽越多，那么升级槽也就越少，这算是牺牲了功能而获得了保护。",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/modifiers/slotless.json
> +            "text": "值得注意的是，额外强化虽是一种无槽位强化，但是它能给予更多强化槽。许多东西都能给予升级槽位，我还听说有些东西还能提供更多的能力槽位。",
```suggestion
            "text": "值得注意的是，额外强化虽是一种无槽位强化，但是它能给予更多强化槽。许多东西都能给予升级槽，我还听说有些东西还能提供更多的能力槽。",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "fluid.tconstruct.flowing_blood": "流动的的血",
```suggestion
    "fluid.tconstruct.flowing_blood": "流动的血",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "block.tconstruct.seared_stone_fluid": "焦黑石头",
原库翻译“焦黑熔石”
如果焦褐要改回去也改吧

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "block.tconstruct.molten_pewter_fluid": "熔融白镴",
pewter有见译成“锡镴”的
这里维持原译也行，因为pewter着实是少见（

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "item.tconstruct.slime_helmet.material.tconstruct.necrotic_bone": "凋零骷髅黏液头颅",
```suggestion
    "item.tconstruct.slime_helmet.material.tconstruct.necrotic_bone": "凋灵骷髅黏液头颅",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "material.tconstruct.skyslime": "碧空史莱姆",
```suggestion
    "material.tconstruct.skyslime": "碧空黏液",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "material.tconstruct.enderslime": "末影史莱姆",
```suggestion
    "material.tconstruct.enderslime": "末影黏液",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "material.tconstruct.earthslime": "大地史莱姆",
```suggestion
    "material.tconstruct.earthslime": "大地黏液",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.haste.2": "急迫II",
这里要加空格吗
要的话下面锋利和幸运一并修改
不要的话修改抢夺

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.aqua_affinity": "水性",
```suggestion
    "modifier.tconstruct.aqua_affinity": "水下速掘",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.aqua_affinity": "水性",
这里要和原版魔咒名统一吗？

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.bane_of_sssss.attack_damage": "对嘶嘶叫的伤害",
```suggestion
    "modifier.tconstruct.bane_of_sssss.attack_damage": "对嘶嘶叫生物的伤害",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.tool_belt": "工具带",
```suggestion
    "modifier.tconstruct.tool_belt": "工具腰带",
```
如果这里用“工具带”，第三本书内需修改

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.shield_strap": "护带",
```suggestion
    "modifier.tconstruct.shield_strap": "副手套环",
```
如果这里用“护带”，第三本书内需修改

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.lightspeed_armor": "光速",
```suggestion
    "modifier.tconstruct.lightspeed_armor": "光动力",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.feather_falling": "羽落",
```suggestion
    "modifier.tconstruct.feather_falling": "摔落保护",
```
原版魔咒名，当然“羽落”也可以

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.pocket_chain.description": "潜行按下交互键时，能够访问工具带或护带所有槽位，还能增加一格槽位",
```suggestion
    "modifier.tconstruct.pocket_chain.description": "潜行按下“护腿交互”键时，能够访问工具带或护带所有槽位，还能增加一格槽位",

```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.shield_strap.description": "按下护腿交互键能够交换护副手物品",
```suggestion
    "modifier.tconstruct.shield_strap.description": "按下“护腿交互”键能够交换护副手物品",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.pockets.description": "这护腿是有口袋的，能让你存储一些额外的物品，这些物品在潜行时按下交互键时能够拿取",
```suggestion
    "modifier.tconstruct.pockets.description": "这护腿是有口袋的，能让你存储一些额外的物品，这些物品在潜行时按下“护腿交互”键时能够拿取",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.slurping.description": "按下交互键时 能引用头盔内的流体",
```suggestion
    "modifier.tconstruct.slurping.description": "按下“头盔交互”键时能饮用头盔内的流体",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "recipe.tconstruct.modifier.pocket_chain": "“锁链行囊”需要“护带”或“工具带”作为前置",
上方如需修改，这里也要

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.soulspeed": "魂速",
```suggestion
    "modifier.tconstruct.soulspeed": "灵魂疾行",
```
原版魔咒名，不过与下方统一或是直接“魂速”都可以

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.double_jump": "二段跳",
```suggestion
    "modifier.tconstruct.double_jump": "多段跳",
```
我记得这里本来是这样来着？

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.autosmelt": "自动熔炼",
```suggestion
    "modifier.tconstruct.autosmelt": "自动烧炼",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.dense": "稠密",
```suggestion
    "modifier.tconstruct.dense": "致密",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.gold_guard": "金卫兵",
莫名笑了（

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.wither_skeleton_disguise.flavor": "走向凋零的1/3之路",
```suggestion
    "modifier.tconstruct.wither_skeleton_disguise.flavor": "走向凋灵的1/3之路",
```

2022-03-26 15:22 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "subtitles.tconstruct.equip.plate": "镶板护甲：叮当作响",
```suggestion
    "subtitles.tconstruct.equip.plate": "镶板盔甲：叮当作响",
```
没看过原版字幕（
只是个意见

2022-03-27 07:52 UTC, ChuijkYahus requested changes

2022-03-27 07:52 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "item.tconstruct.blank_cast": "金质空白铸模",
话说库里不是要求所有材料后不允许出现“质”嘛
怎么这里又改回去了

2022-03-27 07:52 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "item.tconstruct.gold_reinforcement.tooltip": "增加盔甲对药水伤害的防护",
```suggestion
    "item.tconstruct.gold_reinforcement.tooltip": "增加盔甲对魔法伤害的防护",
```

2022-03-27 07:52 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "entity.tconstruct.terracube": "大地史莱姆",
```suggestion
    "entity.tconstruct.terracube": "黏土怪",
```
仅意见

2022-03-27 07:52 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "block.tconstruct.ender_slime_sapling": "末影史莱姆树苗",
```suggestion
    "block.tconstruct.ender_slime_sapling": "末影黏液树苗",
```

2022-03-27 07:52 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "material.tconstruct.ancient_hide": "古法兽皮",
好像是残骸+皮革？

2022-03-27 11:57 UTC, HaloSense reviewed
1

2022-03-27 11:57 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/armor/boots.json
> +        { "text": "这双靴子是为行走而做的，而这正是它们要做的。" },
```suggestion
        { "text": "这双靴子是为行走而生，而这正是它们的使命。" },
```

2022-03-27 11:57 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/armor/pants.json
> +            "text": "不穿裤子出门可不是个好主意，为什么不穿一条即保暖，又方便旅行的裤子呢！",
```suggestion
            "text": "不穿裤子出门可不是个好主意，为什么不穿一条既保暖，又方便旅行的裤子呢！",
```

2022-03-27 11:57 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/armor/pants.json
> +        "低耐久",
```suggestion
        "低耐久值",
```

2022-03-27 11:57 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/furtherreading/puny_craft.json
> +        { "text": "初学者的冶炼和铸造指南，Thruul M'Gon所著 系列中，首本探讨冶炼炉的书籍。" }
```suggestion
        { "text": "初学者的冶炼和铸造指南，Thruul M'Gon所著系列中，首本探讨冶炼炉的书籍。" }
```

2022-03-27 11:57 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/intro/advertisements.json
> +            "text": "我有很多黏液、火药以及其他所能想象的奇妙物品制作出东西！即将在Melvin所著的《工匠装置宝典》中问世。",
```suggestion
            "text": "我有很多黏液、火药以及其他所能想象的奇妙物品制作出的东西！即将在Melvin所著的《工匠装置宝典》中问世。",
```

2022-03-27 11:57 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/intro/partbuilder.json
> +        "text": "制作部件及其简单：制作一个空白模具，将其放入模具槽。选择你想制作的工具部件，然后再放入一种徒手可以塑型的软性材料，就可以获得部件了。",
```suggestion
        "text": "制作部件极其简单：制作一个空白模具，将其放入模具槽。选择你想制作的工具部件，然后再放入一种徒手可以塑型的软性材料，就可以获得部件了。",
```

2022-03-27 11:57 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/intro/storage.json
> +            "text": "所以，你想把多余的部件放在一个专门的箱子里，是这么吗？不是这样啊……虽然不建议，不过也是你的选择吧。"
```suggestion
            "text": "所以，你想把多余的部件放在一个专门的箱子里，是这样吗？不是这样啊……虽然不建议，不过也是你的选择吧。"
```

2022-03-27 11:57 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/intro/tinkerstation2.json
> +            "text": "你也可以在工匠站上为工具添加强化。基础的工匠站只有三个槽位供你组合部件，也就是说你没办法制作范围型工具。其他的工匠大师倒是知晓如何使用四五个部件制作工具。",
```suggestion
            "text": "你也可以在工匠站上为工具添加强化。基础的工匠站只有三个槽位供你组合部件，也就是说你没办法制作宽型工具。其他的工匠大师倒是知晓如何使用四五个部件制作工具。",
```

2022-03-28 11:49 UTC, HaloSense approved these changes
approve

2022-03-28 11:53 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/modifiers/defense.json
> +            "text": "同许多其他的强化属性一样，防御强化需要一个强化槽以装载。很显然，护甲的防御槽越多，那么升级槽也就越少，这算是牺牲了功能而获得了保护。",
警惕西化中文，这个我之后可能再过一遍。

2022-03-28 11:58 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "recipe.tconstruct.modifier.pocket_chain": "“锁链行囊”需要“护带”或“工具带”作为前置",
上方是哪个？来一个link

2022-03-28 12:34 UTC, Cactusstudent reviewed
仅更改部分多余的空格（抠细节了属于是，主文件部分未详细观看，时间不够了）

2022-03-28 12:34 UTC, Cactusstudent commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/armor/vest.json
> +            "text": "胸甲是保护胸膛的重要器物。而且它们穿起来也十分棒",
```suggestion
            "text": "胸甲是保护胸膛的重要器物。而且它们穿起来也十分棒。",
```

2022-03-28 12:34 UTC, Cactusstudent commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/intro/advertisements.json
> +            "text": "你们这群工匠们都给我听好了！我就是独一无 二的§lTHRUUL M'GON§r，我将要推出两本新书：《入 门熔炼术》和《大师熔炼术》。在这两本书中， 我会教你如何使用更好的材料、熔化金属、制作 合金，以及其他知识。",
```suggestion
            "text": "你们这群工匠们都给我听好了！我就是独一无 二的§lTHRUUL M'GON§r，我将要推出两本新书：《入门熔炼术》和《大师熔炼术》。在这两本书中，我会教你如何使用更好的材料、熔化金属、制作合金，以及其他知识。",
```

2022-03-28 12:34 UTC, Cactusstudent commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/furtherreading/gadget_craft.json
> +        { "text": "黏液在日常事物中的妙用。由Melvin所著，探讨如何在世界中寻找材料进行修补的书籍" }
```suggestion
        { "text": "黏液在日常事物中的妙用。由Melvin所著，探讨如何在世界中寻找材料进行修补的书籍。" }
```

2022-03-28 12:34 UTC, Cactusstudent commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/intro/advertisements.json
> +            "text": "没有什么比熔铸炉更神奇的了！详情请阅读 Namea所著的《奇异熔铸术》。",
删除掉Namea之前的空格应该更加正确

2022-03-28 12:34 UTC, Cactusstudent commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/intro/welcome.json
> +            "text": "如果你想知道最新版本有什么变化，请前往 \"What's New\"页面，可以在GitHub页面或是 SlimeKnights的Discord服务器找到跳转链接。 但遗憾的是，我没搞明白怎么在书中添加链接， 所以我没办法直接让你跳转。",
删除SlimeKnights前的空格是否更加合适

2022-03-28 12:34 UTC, Cactusstudent commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/intro/welcome.json
> +            "text": "如果你想知道最新版本有什么变化，请前往 \"What's New\"页面，可以在GitHub页面或是 SlimeKnights的Discord服务器找到跳转链接。 但遗憾的是，我没搞明白怎么在书中添加链接， 所以我没办法直接让你跳转。",
```suggestion
            "text": "如果你想知道最新版本有什么变化，请前往 \"What's New\"页面，可以在GitHub页面或是 SlimeKnights的Discord服务器找到跳转链接。但遗憾的是，我没搞明白怎么在书中添加链接，所以我没办法直接让你跳转。",
```

2022-03-28 12:34 UTC, Cactusstudent commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/modifiers/abilities.json
> +            "text": "Thruul M'Gon所著的《大师熔炼术》有着一整 套可用于工具的能力强化列表，《工匠大百 科》也有介绍。",
```suggestion
            "text": "Thruul M'Gon所著的《大师熔炼术》有着一整套可用于工具的能力强化列表，《工匠大百科》也有介绍。",
```

2022-03-28 12:34 UTC, Cactusstudent commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/modifiers/slotless.json
> +            "text": "Thruul M'Gon所著的《入门熔炼术》有着一整 套可用于工具的无槽位强化列表，《工匠大百 科》也有介绍。",
```suggestion
            "text": "Thruul M'Gon所著的《入门熔炼术》有着一整 套可用于工具的无槽位强化列表，《工匠大百科》也有介绍。",
```

2022-03-28 12:34 UTC, Cactusstudent commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/modifiers/traits.json
> +            "text": "这本书，连同Thruul M'Gon所著的《入门 熔炼术》、《大师熔炼术》和Nemea所著 的《奇异熔铸术》都介绍了一系列材料属性。 而本书和《大师熔炼术》都介绍了工具属性。",
```suggestion
            "text": "这本书，连同Thruul M'Gon所著的《入门熔炼术》、《大师熔炼术》和Nemea所著的《奇异熔铸术》都介绍了一系列材料属性。而本书和《大师熔炼术》都介绍了工具属性。",
```

2022-03-28 12:34 UTC, Cactusstudent commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/modifiers/upgrades.json
> +              "text": "Thruul M'Gon所著的《入门熔炼术》有着一整 套可用于工具的升级列表，《工匠大百科》 也有介绍。",
```suggestion
              "text": "Thruul M'Gon所著的《入门熔炼术》有着一整套可用于工具的升级列表，《工匠大百科》也有介绍。",
```

2022-03-28 12:36 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/modifiers/upgrades.json
> +              "text": "Thruul M'Gon所著的《入门熔炼术》有着一整 套可用于工具的升级列表，《工匠大百科》 也有介绍。",
这些空格是用来换行的

2022-03-28 12:41 UTC, ChuijkYahus commented
话说主文件冲突了

2022-03-28 12:42 UTC, HaloSense commented
我这边还在对着之前的pr改东西

2022-03-28 13:08 UTC, HaloSense requested changes
囊括部分修改建议。
[#14](https://github.com/HaloSense/TiC3-Translation/commit/896da3c6e82c582dad0adfc202396a47eee69513)

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "item.tconstruct.seared_stone_bucket": "焦黑石头桶",
```suggestion
    "block.tconstruct.seared_stone_fluid": "焦黑熔石",
    "fluid.tconstruct.seared_stone": "焦黑熔石",
    "fluid.tconstruct.flowing_seared_stone": "流动的焦黑熔石",
    "item.tconstruct.seared_stone_bucket": "焦黑熔石桶",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "item.tconstruct.scorched_stone_bucket": "焦褐石头桶",
```suggestion
    "block.tconstruct.scorched_stone_fluid": "焦褐熔石",
    "fluid.tconstruct.scorched_stone": "焦褐熔石",
    "fluid.tconstruct.flowing_scorched_stone": "流动的焦褐熔石",
    "item.tconstruct.scorched_stone_bucket": "焦褐熔石桶",
```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "recipe.tconstruct.modifier.pocket_chain": "“锁链行囊”需要“护带”或“工具带”作为前置",
```suggestion
    "recipe.tconstruct.modifier.pocket_chain": "“锁链行囊”需要“副手套环”或“工具腰带”作为前置",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "item.tconstruct.cleaver.description": "劈刀是冶炼术大师必备的武器。再坚韧的敌人在高范围攻击的劈刀面前也难以脱身。",
```suggestion
    "item.tconstruct.cleaver.description": "劈刀是冶炼术大师必备的武器。在高伤害，同时还能大范围攻击的劈刀面前，再棘手的敌人也难以脱身。",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "death.attack.tconstruct.smeltery_heat.player": "%1$s在与%2$s战斗时试图制作熔融的玩家",
```suggestion
    "death.attack.tconstruct.smeltery_heat": "%1$s试图制作熔融玩家",
    "death.attack.tconstruct.smeltery_heat.player": "%1$s在与%2$s战斗时试图制作熔融玩家",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "block.tconstruct.grout.tooltip": "我就是个砖泥！",
这里有点问题，我放个[超链接](https://github.com/HaloSense/TiC3-Translation/commit/896da3c6e82c582dad0adfc202396a47eee69513#r69615856)。

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "block.tconstruct.seared_fuel_tank.tooltip": "冶炼炉的心脏。\n被破坏时仍能保留其中的液体。",
[超链接](https://github.com/HaloSense/TiC3-Translation/commit/896da3c6e82c582dad0adfc202396a47eee69513#r69615940)在此。查证蒸汽等流体是否可以被装入。

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "block.tconstruct.ender_ender_slime_grass.tooltip": "能让你跳得更高，处于末地时生成末影史莱姆",
```suggestion
    "block.tconstruct.ender_vanilla_slime_grass": "末影黏液草方块",
    "block.tconstruct.ender_vanilla_slime_grass.tooltip": "能让你跳得更高，位于末地时生成末影史莱姆",
    "block.tconstruct.ender_earth_slime_grass": "末影黏液草方块",
    "block.tconstruct.ender_earth_slime_grass.tooltip": "能让你跳得更高，位于末地时生成末影史莱姆",
    "block.tconstruct.ender_sky_slime_grass": "末影黏液草方块",
    "block.tconstruct.ender_sky_slime_grass.tooltip": "能让你跳得更高，位于末地时生成末影史莱姆",
    "block.tconstruct.ender_ichor_slime_grass": "末影黏液草方块",
    "block.tconstruct.ender_ichor_slime_grass.tooltip": "能让你跳得更高，位于末地时生成末影史莱姆",
    "block.tconstruct.ender_ender_slime_grass": "末影黏液草方块",
    "block.tconstruct.ender_ender_slime_grass.tooltip": "能让你跳得更高，位于末地时生成末影史莱姆",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "material.tconstruct.bone.encyclopedia": "将0.5点伤害转换为1点穿刺伤害",
[超链接](https://github.com/HaloSense/TiC3-Translation/commit/896da3c6e82c582dad0adfc202396a47eee69513#r69616122)。

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "material.tconstruct.scorched_stone.flavor": "开荒时期的额外奖励。",
看[这里](https://github.com/HaloSense/TiC3-Translation/commit/896da3c6e82c582dad0adfc202396a47eee69513#r69616140)。

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "material.tconstruct.silver.encyclopedia": "对亡灵生物，每级+2.5伤害",
```suggestion
    "material.tconstruct.silver.encyclopedia": "对亡灵生物每级+2.5伤害",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.revitalizing.description": "能够给予更多血量",
```suggestion
    "modifier.tconstruct.revitalizing.description": "能够增加生命值上限",

```
此处已查证工匠大百科，是增加上限，也就是心数。

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.embellishment.description": "护甲的外观可改变，用以匹配不同的材料",
```suggestion
    "modifier.tconstruct.embellishment.description": "改变盔甲的外观，就好像换了一种制作材料。",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.dyed.description": "护甲的外观可改变，用以匹配不同的材料",
```suggestion
    "modifier.tconstruct.dyed.description": "改变盔甲的外观，就好像换了一种制作材料。",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.protection.description": "提升对所有类型伤害的保护！",
```suggestion
    "modifier.tconstruct.protection.description": "提升对所有伤害类型的保护效果！",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.turtle_shell.description": "提升水下保护，还有游泳速度",
```suggestion
    "modifier.tconstruct.turtle_shell.description": "提升在水下的保护效果，并加快游泳速度",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.unarmed.description": "使胸甲强化，从而提升徒手攻击的伤害",
```suggestion
    "modifier.tconstruct.unarmed.description": "提升徒手攻击的伤害",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.unarmed": "徒手攻击",
```suggestion
    "modifier.tconstruct.unarmed": "赤手空拳",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.wings.description": "允许你在半空中跳跃，从而在空中翱翔",
```suggestion
    "modifier.tconstruct.wings.description": "能够在半空中跳跃，翱翔蓝天",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.haste.5": "急迫V",
```suggestion
    "modifier.tconstruct.haste.1": "急迫",
    "modifier.tconstruct.haste.2": "急迫+",
    "modifier.tconstruct.haste.3": "急迫++",
    "modifier.tconstruct.haste.4": "急迫+++",
    "modifier.tconstruct.haste.5": "急迫++++",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.luck.3": "幸运III",
```suggestion
    "modifier.tconstruct.luck.1": "幸运",
    "modifier.tconstruct.luck.2": "幸运+",
    "modifier.tconstruct.luck.3": "幸运++",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "modifier.tconstruct.sharpness.5": "锋利V",
```suggestion
    "modifier.tconstruct.sharpness.1": "锋利",
    "modifier.tconstruct.sharpness.2": "锋利+",
    "modifier.tconstruct.sharpness.3": "锋利++",
    "modifier.tconstruct.sharpness.4": "锋利+++",
    "modifier.tconstruct.sharpness.5": "锋利++++",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "advancements.tconstruct.foundry.blaze.description": "用烈焰血装满一个储罐",
```suggestion
    "advancements.tconstruct.foundry.blaze.title": "烈焰之血",
    "advancements.tconstruct.foundry.blaze.description": "用烈焰之血装满一个储罐",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "advancements.tconstruct.foundry.plate_armor.description": "制作全套的镶板护甲",
```suggestion
    "advancements.tconstruct.foundry.plate_armor.title": "镶板盔甲",
    "advancements.tconstruct.foundry.plate_armor.description": "制作全套的镶板盔甲",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "advancements.tconstruct.world.ender_island.description": "在末地外域找到一座末影史莱姆岛",
```suggestion
    "advancements.tconstruct.world.earth_island.title": "大地黏液岛",
    "advancements.tconstruct.world.earth_island.description": "在海洋中找到一座大地黏液岛",
    "advancements.tconstruct.world.sky_island.title": "碧空黏液岛",
    "advancements.tconstruct.world.sky_island.description": "在空中找到一座碧空黏液岛",
    "advancements.tconstruct.world.blood_island.title": "黏血岛",
    "advancements.tconstruct.world.blood_island.description": "在下界的熔岩海上找到一座黏血岛",
    "advancements.tconstruct.world.ender_island.title": "末影黏液岛",
    "advancements.tconstruct.world.slimesuit.title": "黏液套装",
    "advancements.tconstruct.world.slimesuit.description": "制作出全套的黏液套装",
    "advancements.tconstruct.world.slimeskull.title": "头颅收藏家",
    "advancements.tconstruct.world.slimeskull.description": "合成每种类型的黏液头颅",
    "advancements.tconstruct.world.ender_island.description": "在末地外域找到一座末影黏液岛",

```

2022-03-28 13:08 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "block.tconstruct.part_builder": "部件制造桌",
```suggestion
    "block.tconstruct.part_builder": "部件制造台",

```

2022-03-28 13:09 UTC, HaloSense commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/armor/vest.json
> +            "text": "胸甲是保护胸膛的重要器物。而且它们穿起来也十分棒",
你再看看这句话，没感觉别扭么

2022-03-28 13:10 UTC, Cactusstudent commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/armor/goggles.json
> +        { "text": "它适用于”King“或是“Lemmings”亦或是“KingLemmings”。" },
```suggestion
        { "text": "它适用于“King”或是“Lemmings”亦或是“KingLemmings”。" },
```

2022-03-28 13:12 UTC, ChuijkYahus commented on projects/1.16/assets/tinkers-construct/tconstruct/lang/zh_cn.json
> +    "item.tconstruct.scorched_stone_bucket": "焦褐石头桶",
漏了个字

2022-03-28 13:21 UTC, Cactusstudent commented on projects/1.16/assets/tinkers-construct/tconstruct/book/materials_and_you/zh_cn/armor/vest.json
> +            "text": "胸甲是保护胸膛的重要器物。而且它们穿起来也十分棒",
```suggestion
            "text": "背心是保护上身的重要防具，而且它们穿起来也十分棒",
```

2022-03-28 13:24 UTC, HaloSense approved these changes

2022-03-28 13:26 UTC, HaloSense approved these changes

2022-03-28 13:40 UTC, HaloSense approved these changes

2022-03-28 14:01 UTC, HaloSense approved these changes

2022-03-28 14:04 UTC, merged